version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: joop2oPh
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
