[storage]
adapter = "fs"
path = "./.storage"

[spotify]
client_id = "5ee0bb3d7a014e5599f578a1386f0cb2"
client_secret = "89abcef6e291449bada520bb3b101713"
redirect_uri = "http://localhost:4815/callback"
scopes = [
  "playlist-read-private",
  "playlist-read-collaborative",
  "playlist-modify-public",
  "playlist-modify-private",
  "user-library-read",
  "user-library-modify",
  "user-read-private",
  "user-read-email",
  "user-top-read",
  "user-read-recently-played",
]
