[storage]
adapter = "psql"
host = "localhost:5432"
name = "spotify"
password = "joop2oPh"
user = "postgres"

[spotify]
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"
redirect_uri = "http://localhost:4815/callback"
scopes = [
  "playlist-read-private",
  "playlist-read-collaborative",
  "playlist-modify-public",
  "playlist-modify-private",
  "streaming",
  "ugc-image-upload",
  "user-follow-modify",
  "user-follow-read",
  "user-library-read",
  "user-library-modify",
  "user-read-private",
  "user-read-email",
  "user-top-read",
  "user-read-recently-played",
]
